version: "3.8"
services:
  unifi:
    restart: unless-stopped
    container_name: unifi
    build: .
    image: iwilltry42/unifi:v0.1.3
    ports:
      - 8080:8080 # 8080 - device communication
      - 8443:8443 # 8443 - web admin
      - 8843:8843 # (optional) 8843 - unifi guest portal https redirect
      - 8880:8880 # (optional) 8880 - unifi guest portal
      - 6789:6789 # (optional) 6789 - mobile throughput test
      - 3478:3478/udp # 3478 - STUN
      - 10001:10001/udp # 10001 - AP Discovery
      - 1900:1900/udp # (optional) 1900 - make controller discoverable on L2 network
      - 5514:5514/udp # (optional) 5514 - remote syslog
    depends_on:
      - mongo
    environment:
      MONGO_USER: unifi
      MONGO_PASS: unifi
      # UNIFI_RESET: "true" # reset to defaults
  mongo:
    restart: unless-stopped
    container_name: unifi-mongo
    image: mongo:3.6
    ports:
      - 27017:27017
    volumes:
      - ./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./.local/mongo/data:/data/db # mongo database directory
    environment:
      MONGO_INITDB_ROOT_USERNAME: ubnt-admin
      MONGO_INITDB_ROOT_PASSWORD: ubnt-admin
      MONGO_INITDB_DATABASE: unifi
      MONGO_INITDB_USER: unifi
      MONGO_INITDB_PASS: unifi
  mongo-express:
    container_name: unifi-mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ubnt-admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: ubnt-admin
    depends_on:
      - mongo
